# # config file version
apiVersion: 1


 # list of datasources to insert/update depending
 # on what's available in the datbase
datasources:
   # <string, required> name of the datasource. Required
 - name: carbonapi
   # <string, required> datasource type. Required
   type: graphite
   # <string, required> access mode. direct or proxy. Required
   access: direct
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
   # <string> url
   url: http://local.grafana.clickhouse.pro:8081
   # <string> database password, if used
   password:
   # <string> database user, if used
   user:
   # <string> database name, if used
   database:
   # <bool> enable/disable basic auth
   basicAuth:
   # <string> basic auth username
   basicAuthUser:
   # <string> basic auth password
   basicAuthPassword:
   # <bool> enable/disable with credentials headers
   withCredentials:
   # <bool> mark as default datasource. Max one per org
   isDefault: true
   # <map> fields that will be converted to json and stored in json_data
   jsonData:
      graphiteVersion: "1.0.x"
      tlsAuth: false
      tlsAuthWithCACert: false
   # <string> json object of data that will be encrypted.
   secureJsonData:
     tlsCACert: ""
     tlsClientCert: ""
     tlsClientKey: ""
   version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: false
 - name: clickhouse
   type: vertamedia-clickhouse-datasource
   access: proxy
   orgId: 1
   url: http://local.grafana.clickhouse.pro:8123
   editable: false
